language: generic
os: linux
dist: bionic
services:
  - docker

before_install:
  - docker build -t mfcosta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mfcosta/react-test npm test

after_success:
  - docker build -t mfcosta/multi-client ./client
  - docker build -t mfcosta/multi-nginx ./nginx
  - docker build -t mfcosta/multi-server ./server
  - docker build -t mfcosta/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push mfcosta/multi-client
  - docker push mfcosta/multi-nginx
  - docker push mfcosta/multi-server
  - docker push mfcosta/multi-worker
